exp_hash: 400fc234
hyperparameters:
  data:
    train_loader:
      batch_size: 3
      shuffle: false
  device: cuda
  experiment_dump_to_train_steps_ratio: 5
  experiment_name: mnist_checkpoint_test_v3
  ledger_enable_flushing_threads: true
  ledger_enable_h5_persistence: true
  ledger_flush_interval: 5.0
  ledger_flush_max_rows: 4
  optimizer:
    lr: 0.001
  root_log_dir: C:\Users\GUILLA~1\AppData\Local\Temp\checkpoint_v3_test_disueo80\experiments
  serving_cli: false
  serving_grpc: false
  skip_checkpoint_load: false
  training:
    num_epochs: 11
last_updated: '2026-02-03T17:50:02.339063'
