# Global configuration
device: auto
experiment_name: cls_usecase

# Initially compute natural sorting values, e.g., average intensity. More details in the README.md file.
compute_natural_sort: false

# Experiment parameters
eval_full_to_train_steps_ratio: 50
experiment_dump_to_train_steps_ratio: 50
skip_checkpoint_load: true
tqdm_display: true
is_training: false  # Start training immediately or not

# Configure global dataframe storage
ledger_enable_flushing_threads: true
ledger_enable_h5_persistence: true
ledger_flush_max_rows: 750
ledger_flush_interval: 30.0

# Configure clients
serving_grpc: true
serving_cli: true

# DataLoader parameters
data_root: ../datasets/mnist
data:
  train_loader:
    shuffle: false
    batch_size: 16
  val_loader:
    shuffle: false
    batch_size: 16
  test_loader:
    shuffle: false
    batch_size: 16
    drop_last: false
