device: cuda
experiment_name: bdd_segmentation
data_root: C:/Users/GuillaumePELLUET/OneDrive/Documents/datasets/BDD100k_reduced
root_log_dir: "C:/Users/GuillaumePELLUET/Desktop/trash/weightslab_bdd_tests"
training_steps_to_do: 2000
eval_full_to_train_steps_ratio: 50
num_classes: 6
image_size: 128

# start training immediately or not
is_training: false

# Configure global dataframe storage
enable_h5_persistence: true
ledger_flush_max_rows: 250
ledger_flush_interval: 10.0

data:
  train_loader:
    batch_size: 8
    shuffle: true
    num_workers: 2
  test_loader:
    batch_size: 8
    shuffle: false
    num_workers: 2
