experiment_name: bdd_segmentation
data_root: C:/Users/GuillaumePELLUET/OneDrive/Documents/datasets/BDD100k_reduced
training_steps_to_do: 2000
eval_full_to_train_steps_ratio: 50
num_classes: 6
image_size: 128

# start training immediately or not
is_training: false

data:
  train_loader:
    batch_size: 8
    shuffle: true
    num_workers: 2
  test_loader:
    batch_size: 8
    shuffle: false
    num_workers: 2

device: cuda
