experiment_name: coco_detection
training_steps_to_do: 2000
eval_full_to_train_steps_ratio: 50
num_classes: 6
image_size: 128
tqdm_display: true

# start training immediately or not
is_training: false

data:
  train_loader:
    batch_size: 1
    shuffle: true
    num_workers: 2
    images_dir: C:/Users/GuillaumePELLUET/OneDrive/Documents/datasets/coco/images/val2017
    annotations_file: C:/Users/GuillaumePELLUET/OneDrive/Documents/datasets/coco/annotations/instances_val2017.json
  test_loader:
    batch_size: 1
    shuffle: false
    num_workers: 2
    images_dir: C:/Users/GuillaumePELLUET/OneDrive/Documents/datasets/coco/images/val2017
    annotations_file: C:/Users/GuillaumePELLUET/OneDrive/Documents/datasets/coco/annotations/instances_val2017.json

device: cuda
