device: cuda
root_log_dir: "C:/Users/GuillaumePELLUET/Desktop/trash/weightslab_mnist"
tqdm_display: true
skip_loading: true

experiment_name: Exp_CNN_Test

eval_full_to_train_steps_ratio: 100
experiment_dump_to_train_steps_ratio: 200
skip_checkpoint_load: true

# start training immediately
is_training: true

data:
  train_loader:
    train_shuffle: true
    batch_size: 16
  test_loader:
    test_shuffle: false
    batch_size: 8
    drop_last: false

optimizer:
  lr: 0.01
