device: auto
experiment_name: seg_usecase
data_root: ./datasets/BDD100k_reduced

compute_natural_sort: true

eval_full_to_train_steps_ratio: 100
experiment_dump_to_train_steps_ratio: 150
num_classes: 6
image_size: 128
tqdm_display: true

# start training immediately or not
is_training: false

# Serving
serving_grpc: true
serving_cli: true

# Configure global dataframe storage
ledger_enable_flushing_threads: true
ledger_enable_h5_persistence: true
ledger_flush_max_rows: 2000
ledger_flush_interval: 60.0

data:
  train_loader:
    batch_size: 32
    shuffle: true
  test_loader:
    batch_size: 32
    shuffle: false