# Configuration for mnist training example
# Every parameter wrote at level 0 has as parent experiment_name
device: cpu
root_log_dir: "/tmp/weightslab_mnist"
tqdm_display: true
skip_loading: true
eval_steps: 50

experiment_name: Exp_CNN_Test
training_steps_to_do: 1000
eval_full_to_train_steps_ratio: 50
experiment_dump_to_train_steps_ratio: 67
skip_checkpoint_load: false

data:
  train_dataset:
    train_shuffle: true
    batch_size: 256
  test_dataset:
    test_shuffle: false
    batch_size: 256
    drop_last: false

optimizer:
  lr: 0.01
