device: cuda
root_log_dir: "C:/Users/GuillaumePELLUET/Desktop/trash/ycb_datasets_arch"
tqdm_display: true
tqdm_display_eval: true
skip_loading: true

experiment_name: Exp_YCB_CNN

training_steps_to_do: 10000
eval_full_to_train_steps_ratio: 100
experiment_dump_to_train_steps_ratio: 100
skip_checkpoint_load: false

# start training immediately
is_training: true

data:
  data_dir: "C:/Users/GuillaumePELLUET/OneDrive/Documents/datasets/ycb_datasets_arch/ycb_datasets"
  train_loader:
    train_shuffle: true
    batch_size: 32
  test_loader:
    test_shuffle: false
    batch_size: 8
    drop_last: false

optimizer:
  lr: 0.01
