experiment_name: cls_usecase
device: cuda
root_log_dir: "C:/Users/GuillaumePELLUET/Desktop/trash/ws-classification-usecase"
tqdm_display: true

eval_full_to_train_steps_ratio: 1000
experiment_dump_to_train_steps_ratio: 200
skip_checkpoint_load: true

# start training immediately or not
is_training: false

# Configure global dataframe storage
ledger_enable_h5_persistence: false
ledger_flush_max_rows: 250
ledger_flush_interval: 10.0

data:
  train_loader:
    shuffle: false
    batch_size: 16
  val_loader:
    shuffle: false
    batch_size: 16
  test_loader:
    shuffle: false
    batch_size: 16
    drop_last: false
