device: cuda
root_log_dir: "C:/Users/GuillaumePELLUET/Desktop/trash/weightslab_mnist"
tqdm_display: true
skip_loading: true

experiment_name: Exp_CNN_Test

eval_full_to_train_steps_ratio: 1000
experiment_dump_to_train_steps_ratio: 200
skip_checkpoint_load: true

# start training immediately or not
is_training: true

data:
  train_loader:
    shuffle: false
    batch_size: 16
  val_loader:
    shuffle: false
    batch_size: 16
  test_loader:
    shuffle: false
    batch_size: 16
    drop_last: false

optimizer:
  lr: 0.01
